import type { ThemeDefinition } from "./theme-types";

export interface StyleDef {
  name: string;
  styleID: string;
  fgColorKey: keyof ThemeDefinition["colors"];
  bgColorKey: keyof ThemeDefinition["colors"];
  fontStyle: number;
  keywordClass?: string;
  customText?: string;
}

export interface LexerDef {
  name: string;
  desc: string;
  ext: string;
  styles: StyleDef[];
}

export interface GlobalStyleDef {
  name: string;
  styleID: string;
  fgColorKey?: keyof ThemeDefinition["colors"];
  bgColorKey?: keyof ThemeDefinition["colors"];
  fontStyle?: number;
}

export const lexerTemplate: LexerDef[] = [
  {
    name: "autoit",
    desc: "autoIt",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT LINE",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "2",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "3",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "FUNCTION",
        styleID: "4",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "instre2",
      },
      {
        name: "INSTRUCTION WORD",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "MACRO",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "type1",
      },
      {
        name: "STRING",
        styleID: "7",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "8",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "VARIABLE",
        styleID: "9",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 2,
      },
      {
        name: "SENT",
        styleID: "10",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "type2",
      },
      {
        name: "PREPROCESSOR",
        styleID: "11",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "type3",
      },
      {
        name: "SPECIAL",
        styleID: "12",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "type4",
      },
      {
        name: "EXPAND",
        styleID: "13",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "type5",
      },
      {
        name: "COMOBJ",
        styleID: "14",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "bash",
    desc: "bash",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "ERROR",
        styleID: "1",
        fgColorKey: "activeTab",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "INSTRUCTION WORD",
        styleID: "4",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "NUMBER",
        styleID: "3",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "5",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CHARACTER",
        styleID: "6",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "7",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "IDENTIFIER",
        styleID: "8",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "SCALAR",
        styleID: "9",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "COMMENT LINE",
        styleID: "2",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "PARAM",
        styleID: "10",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "BACKTICKS",
        styleID: "11",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "HERE DELIM",
        styleID: "12",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "HERE Q",
        styleID: "13",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "batch",
    desc: "Batch",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "KEYWORDS",
        styleID: "2",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "instre1",
      },
      {
        name: "LABEL",
        styleID: "3",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "HIDE SYMBOL",
        styleID: "4",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMAND",
        styleID: "5",
        fgColorKey: "identifier",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "VARIABLE",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "7",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "c",
    desc: "C",
    ext: "cw",
    styles: [
      {
        name: "PREPROCESSOR",
        styleID: "9",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "DEFAULT",
        styleID: "11",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "INSTRUCTION WORD",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "instre1",
      },
      {
        name: "TYPE WORD",
        styleID: "16",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "4",
        fgColorKey: "activeTab",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CHARACTER",
        styleID: "7",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "10",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "VERBATIM",
        styleID: "13",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "REGEX",
        styleID: "14",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT LINE",
        styleID: "2",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC",
        styleID: "3",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT LINE DOC",
        styleID: "15",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC KEYWORD",
        styleID: "17",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC KEYWORD ERROR",
        styleID: "18",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "cs",
    desc: "C#",
    ext: "vala",
    styles: [
      {
        name: "PREPROCESSOR",
        styleID: "9",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "DEFAULT",
        styleID: "11",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "INSTRUCTION WORD",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "instre1",
      },
      {
        name: "TYPE WORD",
        styleID: "16",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "4",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CHARACTER",
        styleID: "7",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "10",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "VERBATIM",
        styleID: "13",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "REGEX",
        styleID: "14",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT LINE",
        styleID: "2",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC",
        styleID: "3",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT LINE DOC",
        styleID: "15",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC KEYWORD",
        styleID: "17",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC KEYWORD ERROR",
        styleID: "18",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "cpp",
    desc: "C++",
    ext: "",
    styles: [
      {
        name: "PREPROCESSOR",
        styleID: "9",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "DEFAULT",
        styleID: "11",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "INSTRUCTION WORD",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "instre1",
        customText: "alignas alignof noexcept nullptr static_assert thread_local final override",
      },
      {
        name: "TYPE WORD",
        styleID: "16",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "4",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CHARACTER",
        styleID: "7",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "10",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "VERBATIM",
        styleID: "13",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "REGEX",
        styleID: "14",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT LINE",
        styleID: "2",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC",
        styleID: "3",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT LINE DOC",
        styleID: "15",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC KEYWORD",
        styleID: "17",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC KEYWORD ERROR",
        styleID: "18",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "PREPROCESSOR COMMENT",
        styleID: "23",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "PREPROCESSOR COMMENT DOC",
        styleID: "24",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "css",
    desc: "CSS",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "TAG",
        styleID: "1",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CLASS",
        styleID: "2",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "PSEUDOCLASS",
        styleID: "3",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "UNKNOWN_PSEUDOCLASS",
        styleID: "4",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "IDENTIFIER",
        styleID: "6",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "UNKNOWN_IDENTIFIER",
        styleID: "7",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "VALUE",
        styleID: "8",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "COMMENT",
        styleID: "9",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "ID",
        styleID: "10",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "IMPORTANT",
        styleID: "11",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "DIRECTIVE",
        styleID: "12",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "nfo",
    desc: "Dos Style",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "32",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "erlang",
    desc: "Erlang",
    ext: "",
    styles: [
      {
        name: "DEFAULT STYLE",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "DEFAULT COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "FUNCTION COMMENT",
        styleID: "14",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "MODULE COMMENT",
        styleID: "15",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "DOCUMENTATION HELPER IN COMMENT",
        styleID: "16",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "type3",
      },
      {
        name: "DOCUMENTATION MACRO IN COMMENT",
        styleID: "17",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 3,
        keywordClass: "type4",
      },
      {
        name: "VARIABLE",
        styleID: "2",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "3",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "5",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CHARACTER",
        styleID: "9",
        fgColorKey: "activeTab",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "MACRO",
        styleID: "10",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "MACRO QUOTED",
        styleID: "19",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "RECORD",
        styleID: "11",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "RECORD QUOTED",
        styleID: "20",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "ATOM",
        styleID: "7",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "ATOM QUOTED",
        styleID: "18",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NODE NAME",
        styleID: "13",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NODE NAME QUOTED",
        styleID: "21",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "RESERVED WORDS",
        styleID: "4",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "BUILT-IN FUNCTIONS",
        styleID: "22",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre2",
      },
      {
        name: "FUNCTION NAME",
        styleID: "8",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "MODULE NAME",
        styleID: "23",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "MODULE ATTRIBUTES",
        styleID: "24",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "type2",
      },
      {
        name: "PREPROCESSOR",
        styleID: "12",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "type1",
      },
      {
        name: "OPERATORS",
        styleID: "6",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "UNKNOWN: ERROR",
        styleID: "31",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "errorlist",
    desc: "ErrorList",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "ERROR",
        styleID: "1",
        fgColorKey: "activeTab",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "WARNING",
        styleID: "2",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "INFO",
        styleID: "3",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "go",
    desc: "Go",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTLINE",
        styleID: "2",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTDOC",
        styleID: "3",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "4",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "KEYWORD",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "STRING",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CHARACTER",
        styleID: "7",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "PREPROCESSOR",
        styleID: "9",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "10",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "IDENTIFIER",
        styleID: "11",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRINGRAW",
        styleID: "13",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTDOCKEYWORD",
        styleID: "17",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "COMMENTDOCKEYWORDERROR",
        styleID: "18",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "haskell",
    desc: "Haskell",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "IDENTIFIER",
        styleID: "1",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "KEYWORD",
        styleID: "2",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "NUMBER",
        styleID: "3",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "4",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CHARACTER",
        styleID: "5",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CLASS",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "MODULE",
        styleID: "7",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CAPITAL",
        styleID: "8",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "DATA",
        styleID: "9",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "IMPORT",
        styleID: "10",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "11",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "INSTANCE",
        styleID: "12",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTLINE",
        styleID: "13",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTBLOCK",
        styleID: "14",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTBLOCK2",
        styleID: "15",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTBLOCK3",
        styleID: "16",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "html",
    desc: "HTML",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "9",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "5",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "DOUBLESTRING",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "SINGLESTRING",
        styleID: "7",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "TAG",
        styleID: "1",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "TAGEND",
        styleID: "11",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "TAGUNKNOWN",
        styleID: "2",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "ATTRIBUTE",
        styleID: "3",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "ATTRIBUTEUNKNOWN",
        styleID: "4",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "SGMLDEFAULT",
        styleID: "21",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CDATA",
        styleID: "17",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "VALUE",
        styleID: "19",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "ENTITY",
        styleID: "10",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "ini",
    desc: "ini file",
    ext: "cfg conf",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "SECTION",
        styleID: "2",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "ASSIGNMENT",
        styleID: "3",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "DEFVAL",
        styleID: "4",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "java",
    desc: "Java",
    ext: "",
    styles: [
      {
        name: "PREPROCESSOR",
        styleID: "9",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "DEFAULT",
        styleID: "11",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "INSTRUCTION WORD",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "instre1",
        customText:
          "@Override @SuppressWarnings @SafeVarargs @FunctionalInterface @Retention @Documented @Target @Inherited @Repeatable @Deprecated",
      },
      {
        name: "TYPE WORD",
        styleID: "16",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "4",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CHARACTER",
        styleID: "7",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "10",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "VERBATIM",
        styleID: "13",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "REGEX",
        styleID: "14",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT LINE",
        styleID: "2",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC",
        styleID: "3",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT LINE DOC",
        styleID: "15",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC KEYWORD",
        styleID: "17",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC KEYWORD ERROR",
        styleID: "18",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "javascript",
    desc: "JavaScript (embedded)",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "41",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "45",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "WORD",
        styleID: "46",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "KEYWORD",
        styleID: "47",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 3,
        keywordClass: "instre1",
      },
      {
        name: "DOUBLESTRING",
        styleID: "48",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "SINGLESTRING",
        styleID: "49",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "SYMBOLS",
        styleID: "50",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "REGEX",
        styleID: "52",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "42",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTLINE",
        styleID: "43",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTDOC",
        styleID: "44",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "json",
    desc: "JSON",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "11",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "4",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING DOUBLE QUOTE",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING SINGLE QUOTE",
        styleID: "7",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "BOOLEAN NULL",
        styleID: "5",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "OPERATOR",
        styleID: "10",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
    ],
  },
  {
    name: "json5",
    desc: "JSON5",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "1",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "2",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "IDENTIFIER",
        styleID: "3",
        fgColorKey: "identifier",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "KEYWORD",
        styleID: "4",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "OPERATOR",
        styleID: "5",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "COMMENT LINE",
        styleID: "6",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT BLOCK",
        styleID: "7",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "kix",
    desc: "KiXtart",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "31",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "2",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING2",
        styleID: "3",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "4",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "VAR",
        styleID: "5",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "MACRO",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "instre2",
      },
      {
        name: "INSTRUCTION WORD",
        styleID: "7",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "FUNCTION",
        styleID: "8",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "type1",
      },
      {
        name: "OPERATOR",
        styleID: "9",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
    ],
  },
  {
    name: "latex",
    desc: "LaTeX",
    ext: "",
    styles: [
      {
        name: "WHITE SPACE",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMAND",
        styleID: "1",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "TAG OPENING",
        styleID: "2",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "MATH INLINE",
        styleID: "3",
        fgColorKey: "activeTab",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "4",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "TAG CLOSING",
        styleID: "5",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "MATH BLOCK",
        styleID: "6",
        fgColorKey: "activeTab",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT BLOCK",
        styleID: "7",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "VERBATIM SEGMENT",
        styleID: "8",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "SHORT COMMAND",
        styleID: "9",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "SPECIAL CHAR",
        styleID: "10",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMAND OPTIONAL ARGUMENT",
        styleID: "11",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "SYNTAX ERROR",
        styleID: "12",
        fgColorKey: "foreground",
        bgColorKey: "activeTab",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "lisp",
    desc: "LISP",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTLINE",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "2",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "FUNCTION WORD",
        styleID: "3",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "FUNCTION WORD2",
        styleID: "4",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre2",
      },
      {
        name: "SYMBOL",
        styleID: "5",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "STRING",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "IDENTIFIER",
        styleID: "9",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "10",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "type1",
      },
      {
        name: "SPECIAL",
        styleID: "11",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "12",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "lua",
    desc: "Lua",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT LINE",
        styleID: "2",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC",
        styleID: "3",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "LITERALSTRING",
        styleID: "8",
        fgColorKey: "activeTab",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "PREPROCESSOR",
        styleID: "9",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "INSTRUCTION WORD",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "NUMBER",
        styleID: "4",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CHARACTER",
        styleID: "7",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "10",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "FUNC1",
        styleID: "13",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre2",
      },
      {
        name: "FUNC2",
        styleID: "14",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "type1",
      },
      {
        name: "FUNC3",
        styleID: "15",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 3,
        keywordClass: "type2",
      },
      {
        name: "IDENTIFIER",
        styleID: "11",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "LABEL",
        styleID: "20",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
    ],
  },
  {
    name: "makefile",
    desc: "Makefile",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "PREPROCESSOR",
        styleID: "2",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "IDENTIFIER",
        styleID: "3",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "4",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "TARGET",
        styleID: "5",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "IDEOL",
        styleID: "9",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 2,
      },
    ],
  },
  {
    name: "matlab",
    desc: "Matlab",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMAND",
        styleID: "2",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "3",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "INSTRUCTION WORD",
        styleID: "4",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "STRING",
        styleID: "5",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "6",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "IDENTIFIER",
        styleID: "7",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "DOUBLE QUOTE STRING",
        styleID: "8",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "md",
    desc: "MD",
    ext: "",
    styles: [
      {
        name: "PREPROCESSOR",
        styleID: "9",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "DEFAULT",
        styleID: "11",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "INSTRUCTION WORD",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "instre1",
      },
      {
        name: "TYPEWORD",
        styleID: "16",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "type1",
      },
      {
        name: "NUMBER",
        styleID: "4",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CHARACTER",
        styleID: "7",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "10",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "VERBATIM",
        styleID: "13",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "REGEX",
        styleID: "14",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT LINE",
        styleID: "2",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC",
        styleID: "3",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT LINE DOC",
        styleID: "15",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC KEYWORD",
        styleID: "17",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC KEYWORD ERROR",
        styleID: "18",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "objc",
    desc: "Objective-C",
    ext: "",
    styles: [
      {
        name: "PREPROCESSOR",
        styleID: "9",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "DEFAULT",
        styleID: "11",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "INSTRUCTION WORD",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "instre1",
      },
      {
        name: "TYPE WORD",
        styleID: "16",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "4",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CHARACTER",
        styleID: "7",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "10",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "VERBATIM",
        styleID: "13",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "REGEX",
        styleID: "14",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT LINE",
        styleID: "2",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC",
        styleID: "3",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT LINE DOC",
        styleID: "15",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC KEYWORD",
        styleID: "17",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC KEYWORD ERROR",
        styleID: "18",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "pascal",
    desc: "Pascal",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "IDENTIFIER",
        styleID: "1",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "2",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT LINE",
        styleID: "3",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC",
        styleID: "4",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "PREPROCESSOR",
        styleID: "5",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "PREPROCESSOR2",
        styleID: "6",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "7",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "HEX NUMBER",
        styleID: "8",
        fgColorKey: "activeTab",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "INSTRUCTION WORD",
        styleID: "9",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "STRING",
        styleID: "10",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CHARACTER",
        styleID: "12",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "13",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "ASM",
        styleID: "14",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 1,
      },
    ],
  },
  {
    name: "perl",
    desc: "Perl",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "ERROR",
        styleID: "1",
        fgColorKey: "activeTab",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTLINE",
        styleID: "2",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "POD",
        styleID: "3",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "4",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "WORD",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "STRING",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CHARACTER",
        styleID: "7",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "PUNCTUATION",
        styleID: "8",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "PREPROCESSOR",
        styleID: "9",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "10",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "IDENTIFIER",
        styleID: "11",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "SCALAR",
        styleID: "12",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "ARRAY",
        styleID: "13",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "HASH",
        styleID: "14",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "SYMBOL TABLE",
        styleID: "15",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "REGEX",
        styleID: "17",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "REGSUBST",
        styleID: "18",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "LONGQUOTE",
        styleID: "19",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "BACKTICKS",
        styleID: "20",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "DATA SECTION",
        styleID: "21",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "HERE DELIM",
        styleID: "22",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "HERE Q",
        styleID: "23",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "POD VERBATIM",
        styleID: "24",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "SUBROUTINE",
        styleID: "25",
        fgColorKey: "identifier",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "WORD LIST",
        styleID: "26",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "FUNCTION",
        styleID: "27",
        fgColorKey: "identifier",
        bgColorKey: "background",
        fontStyle: 1,
      },
    ],
  },
  {
    name: "php",
    desc: "php",
    ext: "",
    styles: [
      {
        name: "QUESTION MARK",
        styleID: "18",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "DEFAULT",
        styleID: "118",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "119",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING VARIABLE",
        styleID: "126",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "SIMPLESTRING",
        styleID: "120",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "WORD",
        styleID: "121",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "NUMBER",
        styleID: "122",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "VARIABLE",
        styleID: "123",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "124",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTLINE",
        styleID: "125",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "127",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "powershell",
    desc: "PowerShell",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "2",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CHARACTER",
        styleID: "3",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "4",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "VARIABLE",
        styleID: "5",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "OPERATOR",
        styleID: "6",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "INSTRUCTION WORD",
        styleID: "8",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "CMDLET",
        styleID: "9",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "instre2",
      },
      {
        name: "ALIAS",
        styleID: "10",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "type1",
      },
      {
        name: "COMMENT STREAM",
        styleID: "13",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "HERE STRING",
        styleID: "14",
        fgColorKey: "activeTab",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "HERE CHARACTER",
        styleID: "15",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC KEYWORD",
        styleID: "16",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "type4",
      },
    ],
  },
  {
    name: "props",
    desc: "Properties file",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "SECTION",
        styleID: "2",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "ASSIGNMENT",
        styleID: "3",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "DEFVAL",
        styleID: "4",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "python",
    desc: "Python",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTLINE",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "2",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "3",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CHARACTER",
        styleID: "4",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "KEYWORDS",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "TRIPLE",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "TRIPLEDOUBLE",
        styleID: "7",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CLASSNAME",
        styleID: "8",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "DEFNAME",
        styleID: "9",
        fgColorKey: "identifier",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "10",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "IDENTIFIER",
        styleID: "11",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTBLOCK",
        styleID: "12",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "DECORATOR",
        styleID: "15",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 2,
      },
    ],
  },
  {
    name: "r",
    desc: "R",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 2,
      },
      {
        name: "INSTRUCTION WORD",
        styleID: "2",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "BASE WORD",
        styleID: "3",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "instre2",
      },
      {
        name: "KEYWORD",
        styleID: "4",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "type1",
      },
      {
        name: "NUMBER",
        styleID: "5",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING2",
        styleID: "7",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "8",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "INFIX",
        styleID: "10",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "IDENTIFIER",
        styleID: "9",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "ruby",
    desc: "Ruby",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "ERROR",
        styleID: "1",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTLINE",
        styleID: "2",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "POD",
        styleID: "3",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "4",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "INSTRUCTION",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "STRING",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CHARACTER",
        styleID: "7",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CLASS NAME",
        styleID: "8",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "DEF NAME",
        styleID: "9",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "OPERATOR",
        styleID: "10",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "IDENTIFIER",
        styleID: "11",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "REGEX",
        styleID: "12",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "GLOBAL",
        styleID: "13",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "SYMBOL",
        styleID: "14",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "MODULE NAME",
        styleID: "15",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "INSTANCE VAR",
        styleID: "16",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CLASS VAR",
        styleID: "17",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "BACKTICKS",
        styleID: "18",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "DATA SECTION",
        styleID: "19",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING Q",
        styleID: "24",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "rust",
    desc: "Rust",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "11",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "WHITESPACE",
        styleID: "0",
        fgColorKey: "whitespace",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "BLOCK COMMENT",
        styleID: "2",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "LINE COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "BLOCK DOC COMMENT",
        styleID: "3",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "LINE DOC COMMENT",
        styleID: "15",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "4",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "KEYWORDS 1",
        styleID: "5",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "type1",
      },
      {
        name: "KEYWORDS 2",
        styleID: "7",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre2",
      },
      {
        name: "KEYWORDS 3",
        styleID: "14",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "type1",
      },
      {
        name: "KEYWORDS 4",
        styleID: "9",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "type2",
      },
      {
        name: "KEYWORDS 5",
        styleID: "10",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "type3",
      },
      {
        name: "KEYWORDS 6",
        styleID: "16",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "type4",
      },
      {
        name: "KEYWORDS 7",
        styleID: "12",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "type5",
      },
      {
        name: "REGULAR STRING",
        styleID: "13",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "RAW STRING",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CHARACTER",
        styleID: "8",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "24",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "IDENTIFIER",
        styleID: "17",
        fgColorKey: "identifier",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "LIFETIME",
        styleID: "18",
        fgColorKey: "identifier",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "MACRO",
        styleID: "19",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "LEXICAL ERROR",
        styleID: "20",
        fgColorKey: "foreground",
        bgColorKey: "activeTab",
        fontStyle: 0,
      },
      {
        name: "BYTE STRING",
        styleID: "21",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "RAW BYTE STRING",
        styleID: "22",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "BYTE CHARACTER",
        styleID: "23",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "searchResult",
    desc: "Search result",
    ext: "",
    styles: [
      {
        name: "Search Header",
        styleID: "1",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "File Header",
        styleID: "2",
        fgColorKey: "identifier",
        bgColorKey: "background",
        fontStyle: 2,
      },
      {
        name: "Line Number",
        styleID: "3",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "Hit Word",
        styleID: "4",
        fgColorKey: "activeTab",
        bgColorKey: "selection",
        fontStyle: 0,
      },
      {
        name: "Current line background colour",
        styleID: "6",
        fgColorKey: "foreground",
        bgColorKey: "selection",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "sql",
    desc: "SQL",
    ext: "",
    styles: [
      {
        name: "KEYWORD",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "instre1",
      },
      {
        name: "NUMBER",
        styleID: "4",
        fgColorKey: "activeTab",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING2",
        styleID: "7",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "10",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT LINE",
        styleID: "2",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT DOC",
        styleID: "3",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT LINE DOC",
        styleID: "15",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "swift",
    desc: "Swift",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTLINE",
        styleID: "2",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTDOC",
        styleID: "3",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "4",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "KEYWORD",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "STRING",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CHARACTER",
        styleID: "7",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "10",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "IDENTIFIER",
        styleID: "11",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRINGINTERPOL",
        styleID: "13",
        fgColorKey: "identifier",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTDOCKEYWORD",
        styleID: "17",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "COMMENTDOCKEYWORDERROR",
        styleID: "18",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "tcl",
    desc: "TCL",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTLINE",
        styleID: "2",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "3",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "WORD IN QUOTE",
        styleID: "4",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "INSTRUCTION WORD",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "BRACE",
        styleID: "6",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "WORD",
        styleID: "7",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "WORD8",
        styleID: "8",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "WORD7",
        styleID: "9",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "10",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "IDENTIFIER",
        styleID: "11",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "12",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "WORD2",
        styleID: "13",
        fgColorKey: "identifier",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre2",
      },
      {
        name: "WORD3",
        styleID: "14",
        fgColorKey: "identifier",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "type1",
      },
      {
        name: "WORD4",
        styleID: "15",
        fgColorKey: "identifier",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "type2",
      },
      {
        name: "WORD5",
        styleID: "16",
        fgColorKey: "identifier",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "type3",
      },
      {
        name: "WORD6",
        styleID: "17",
        fgColorKey: "identifier",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "type4",
      },
    ],
  },
  {
    name: "toml",
    desc: "TOML",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "KEY",
        styleID: "2",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "STRING",
        styleID: "3",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "4",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "DATE",
        styleID: "5",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "BOOLEAN",
        styleID: "6",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "BAREKEY",
        styleID: "7",
        fgColorKey: "identifier",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "BASIC STRING",
        styleID: "8",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "LITERAL STRING",
        styleID: "9",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "ESCAPE SEQUENCE",
        styleID: "10",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "ERROR",
        styleID: "11",
        fgColorKey: "activeTab",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "typescript",
    desc: "TypeScript (embedded)",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "41",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "45",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "WORD",
        styleID: "46",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "KEYWORD",
        styleID: "47",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 3,
        keywordClass: "instre1",
      },
      {
        name: "DOUBLESTRING",
        styleID: "48",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "SINGLESTRING",
        styleID: "49",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "SYMBOLS",
        styleID: "50",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "REGEX",
        styleID: "52",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "42",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTLINE",
        styleID: "43",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENTDOC",
        styleID: "44",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "vb",
    desc: "VB / VBS",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "7",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "2",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "WORD",
        styleID: "3",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
        keywordClass: "instre1",
      },
      {
        name: "STRING",
        styleID: "4",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "PREPROCESSOR",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "6",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "DATE",
        styleID: "8",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "vhdl",
    desc: "VHDL",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT LINE BANG",
        styleID: "2",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "3",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING",
        styleID: "4",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "OPERATOR",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "IDENTIFIER",
        styleID: "6",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "UNCLOSED STRING",
        styleID: "7",
        fgColorKey: "activeTab",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "KEYWORD",
        styleID: "8",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "STD OPERATOR",
        styleID: "9",
        fgColorKey: "smartHighlight",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre2",
      },
      {
        name: "ATTRIBUTE",
        styleID: "10",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STANDARD FUNCTION",
        styleID: "11",
        fgColorKey: "identifier",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "type1",
      },
      {
        name: "STANDARD PACKAGE",
        styleID: "12",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STANDARD TYPE",
        styleID: "13",
        fgColorKey: "fold",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "USER WORD",
        styleID: "14",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "STRING EOL",
        styleID: "15",
        fgColorKey: "activeTab",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "xml",
    desc: "XML",
    ext: "xaml svg xul vcxproj csproj vbproj fsproj lsxtproj shproj xproj ccproj jsproj sqlproj dbproj msbuildproj props",
    styles: [
      {
        name: "XMLSTART",
        styleID: "12",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "XMLEND",
        styleID: "13",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "COMMENT",
        styleID: "9",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "NUMBER",
        styleID: "5",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "DOUBLESTRING",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "SINGLESTRING",
        styleID: "7",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "TAG",
        styleID: "1",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "TAGEND",
        styleID: "11",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "TAGUNKNOWN",
        styleID: "2",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "ATTRIBUTE",
        styleID: "3",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "ATTRIBUTEUNKNOWN",
        styleID: "4",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "SGMLDEFAULT",
        styleID: "21",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "CDATA",
        styleID: "17",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
  {
    name: "yaml",
    desc: "YAML",
    ext: "",
    styles: [
      {
        name: "DEFAULT",
        styleID: "0",
        fgColorKey: "foreground",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "IDENTIFIER",
        styleID: "2",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "COMMENT",
        styleID: "1",
        fgColorKey: "indentGuide",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "INSTRUCTION WORD",
        styleID: "3",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 1,
        keywordClass: "instre1",
      },
      {
        name: "NUMBER",
        styleID: "4",
        fgColorKey: "warning",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "REFERENCE",
        styleID: "5",
        fgColorKey: "operator",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "DOCUMENT",
        styleID: "6",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
      {
        name: "TEXT",
        styleID: "7",
        fgColorKey: "activeTab",
        bgColorKey: "background",
        fontStyle: 1,
      },
      {
        name: "ERROR",
        styleID: "8",
        fgColorKey: "url",
        bgColorKey: "background",
        fontStyle: 0,
      },
    ],
  },
];

export const globalStylesTemplate: GlobalStyleDef[] = [
  {
    name: "Global override",
    styleID: "0",
    fgColorKey: "foreground",
    bgColorKey: "background",
    fontStyle: 0,
  },
  {
    name: "Default Style",
    styleID: "32",
    fgColorKey: "foreground",
    bgColorKey: "background",
    fontStyle: 0,
  },
  {
    name: "Indent guideline style",
    styleID: "37",
    fgColorKey: "indentGuide",
    bgColorKey: "background",
    fontStyle: 0,
  },
  {
    name: "Brace highlight style",
    styleID: "34",
    fgColorKey: "foreground",
    bgColorKey: "fold",
    fontStyle: 1,
  },
  {
    name: "Bad brace colour",
    styleID: "35",
    fgColorKey: "foreground",
    bgColorKey: "activeTab",
    fontStyle: 0,
  },
  {
    name: "Current line background colour",
    styleID: "0",
    fgColorKey: "foreground",
    bgColorKey: "lineHighlight",
    fontStyle: 0,
  },
  {
    name: "Selected text colour",
    styleID: "0",
    fgColorKey: "foreground",
    bgColorKey: "selection",
    fontStyle: 0,
  },
  {
    name: "Caret colour",
    styleID: "2069",
    fgColorKey: "foreground",
    bgColorKey: "background",
    fontStyle: 0,
  },
  {
    name: "Edge colour",
    styleID: "0",
    fgColorKey: "foreground",
    bgColorKey: "background",
    fontStyle: 0,
  },
  {
    name: "Line number margin",
    styleID: "33",
    fgColorKey: "fold",
    bgColorKey: "background",
    fontStyle: 0,
  },
  {
    name: "Fold",
    styleID: "0",
    fgColorKey: "fold",
    bgColorKey: "background",
    fontStyle: 0,
  },
  {
    name: "Fold active",
    styleID: "0",
    fgColorKey: "fold",
    bgColorKey: "background",
    fontStyle: 0,
  },
  {
    name: "Fold margin",
    styleID: "0",
    fgColorKey: "background",
    bgColorKey: "background",
    fontStyle: 0,
  },
  {
    name: "White space symbol",
    styleID: "0",
    fgColorKey: "indentGuide",
    bgColorKey: "background",
    fontStyle: 0,
  },
  {
    name: "URL hovered",
    styleID: "0",
    fgColorKey: "url",
    bgColorKey: "background",
    fontStyle: 0,
  },
  {
    name: "Tags attribute",
    styleID: "26",
    fgColorKey: "foreground",
    bgColorKey: "background",
    fontStyle: 0,
  },
  {
    name: "Tags match highlighting",
    styleID: "27",
    fgColorKey: "background",
    bgColorKey: "fold",
    fontStyle: 0,
  },
  {
    name: "Smart HighLighting",
    styleID: "29",
    fgColorKey: "foreground",
    bgColorKey: "smartHighlight",
    fontStyle: 1,
  },
  {
    name: "Active tab focused indicator",
    styleID: "0",
    fgColorKey: "activeTab",
    fontStyle: 0,
  },
];
